---
title: "Ranchos de Pesca em SC"
subtitle: "em relação à emissão de TAUS"
author: "Humberto Pereira Almeida"
date: "06/12/2019"
output: 
  beamer_presentation:
    theme: Copenhagen
    includes:
      in_header: preamble.tex
    keep_tex: true
classoption: 8pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, dev = "tikzDevice")
```


## Atual

\begin{center}
\smartdiagramset{custom/.style={
  satellite font=\tiny,
  satellite size=1.25cm,
  planet font=\footnotesize,
  planet size=1.25cm,
  distance planet-satellite=3cm,
  distance planet-text=.1cm
  }
}
\smartdiagramset{custom}
\smartdiagramanimated[constellation diagram]{
\textbf{Pescador}, \textbf{SPU}, \textbf{Município}, \textbf{ICMBIO}, \textbf{BB}, \textbf{INSS}, \textbf{RFB}, \textbf{Capitania dos Portos}, \textbf{MAPA}
}
\end{center}

## Desejado

\begin{center}
\smartdiagramset{
  satellite font=\tiny,
  satellite size=1.25cm,
  planet font=\footnotesize,
  planet size=1.25cm,
  distance planet-satellite=3cm,
  distance planet-text=.1cm,
  /tikz/connection planet satellite/.append style={<-}
}
\smartdiagramadd[connected constellation diagram]{
\textbf{Pescador}, \textbf{SPU}, \textbf{Município}, \textbf{ICMBIO}, \textbf{BB}, \textbf{INSS}, \textbf{RFB}, \textbf{Capitania dos Portos}, \textbf{MAPA}
}{}
\smartdiagramconnect{<->}{planet/satellite2}
\end{center}

## Desejado {.plain}

\begin{center}

\smartdiagramset{custom/.style={
    arrow tip=latex,
    arrow line width=.5pt,
    module shape=circle,
    font=\tiny,
    text width=1cm,
    circular distance=3cm,
    border color=none,
    additions={
        additional item font=\scriptsize,
        additional item fill color=lightgray!50,
        additional item offset=1.20cm,
        additional item text width=1.5cm,
        additional item width=2cm
        }
    }
}

\smartdiagramset{custom}
\smartdiagramadd[circular diagram:clockwise]
    {
    \textbf{SPU} \\ TAUS,
    \textbf{Munic\'{i}pio} \\ Nada a opor,
    \textbf{ICMBio} \\ Nada a opor,
    \textbf{BB} \\ Comprova\c{c}\~{a}o servidor p\'{u}blico,
    \textbf{INSS} \\  CNIS ,
    \textbf{RFB} \\ CEI,
    \textbf{Capitania} \\ Carteira POP e Reg. Embarcação}
    {right of module7/ Pescador}

\end{center}

## Entidades

\begin{block}{Entidades Envolvidas}
\begin{enumerate}
  \item Associação de Pescadores;
  \item Associações Municipais;
  \item Sindicatos;
  \item Colônias de Pescadores;
  \item Universidades
  \item SEBRAE
\end{enumerate}
\end{block}


## Órgãos de fiscalização

\begin{exampleblock}{\'{O}rg\~{a}os de Fiscaliza\c{c}\~{a}o}
\begin{enumerate}
  \item Ministério Público Estadual e Federal;
  \item IBAMA;
  \item IMA;
  \item Polícia Ambiental;
  \item Polícia Federal;
  \item Meio Ambiente Municipal;
  \item SPU
\end{enumerate}
\end{exampleblock}


## Judiciais

\begin{alertblock}{Demandas de Natureza Jurídica}
\begin{enumerate}
  \item Poder Judiciário Estadual e Federal
\end{enumerate}
\end{alertblock}
